export const dummyMovieListData = [
  {
    adult: false,
    backdrop_path: "/rTJ8LLzT9NPRJA2dnQs0241bMRn.jpg",
    genre_ids: [27, 53],
    id: 1008042,
    original_language: "en",
    original_title: "Talk to Me",
    overview:
      "When a group of friends discover how to conjure spirits using an embalmed hand, they become hooked on the new thrill, until one of them goes too far and unleashes terrifying supernatural forces.",
    popularity: 1370.306,
    poster_path: "/kdPMUMJzyYAc4roD52qavX0nLIC.jpg",
    release_date: "2023-07-26",
    title: "Talk to Me",
    video: false,
    vote_average: 7.2,
    vote_count: 386,
  },
  {
    adult: false,
    backdrop_path: "/ctMserH8g2SeOAnCw5gFjdQF8mo.jpg",
    genre_ids: [35, 12, 14],
    id: 346698,
    original_language: "en",
    original_title: "Barbie",
    overview:
      "Barbie and Ken are having the time of their lives in the colorful and seemingly perfect world of Barbie Land. However, when they get a chance to go to the real world, they soon discover the joys and perils of living among humans.",
    popularity: 3661.8,
    poster_path: "/iuFNMS8U5cb6xfzi51Dbkovj7vM.jpg",
    release_date: "2023-07-19",
    title: "Barbie",
    video: false,
    vote_average: 7.3,
    vote_count: 4286,
  },
  {
    adult: false,
    backdrop_path: "/nYDPmxvl0if5vHBBp7pDYGkTFc7.jpg",
    genre_ids: [27],
    id: 709631,
    original_language: "en",
    original_title: "Cobweb",
    overview:
      "Eight year old Peter is plagued by a mysterious, constant tapping from inside his bedroom wall—one that his parents insist is all in his imagination. As Peter's fear intensifies, he believes that his parents could be hiding a terrible, dangerous secret and questions their trustworthiness.",
    popularity: 268.402,
    poster_path: "/cGXFosYUHYjjdKrOmA0bbjvzhKz.jpg",
    release_date: "2023-07-19",
    title: "Cobweb",
    video: false,
    vote_average: 6.8,
    vote_count: 315,
  },
  //   {
  //     adult: false,
  //     backdrop_path: '/iEFuHjqrE059SmflBva1JzDJutE.jpg',
  //     genre_ids: [ 16, 10751, 28, 14, 10749 ],
  //     id: 496450,
  //     original_language: 'fr',
  //     original_title: 'Miraculous - le film',
  //     overview: 'A life of an ordinary Parisian teenager Marinette goes superhuman when she becomes Ladybug. Bestowed with magical powers of creation, Ladybug must unite with her opposite, Cat Noir, to save Paris as a new villain unleashes chaos unto the city.',
  //     popularity: 251.343,
  //     poster_path: '/bBON9XO9Ek0DjRwMBnJNCwC96Cd.jpg',
  //     release_date: '2023-07-05',
  //     title: 'Miraculous: Ladybug & Cat Noir, The Movie',
  //     video: false,
  //     vote_average: 7.9,
  //     vote_count: 553
  //   },
  //   {
  //     adult: false,
  //     backdrop_path: '/waBWlJlMpyFb7STkFHfFvJKgwww.jpg',
  //     genre_ids: [ 28, 18 ],
  //     id: 678512,
  //     original_language: 'en',
  //     original_title: 'Sound of Freedom',
  //     overview: 'The story of Tim Ballard, a former US government agent, who quits his job in order to devote his life to rescuing children from global sex traffickers.',
  //     popularity: 806.113,
  //     poster_path: '/kSf9svfL2WrKeuK8W08xeR5lTn8.jpg',
  //     release_date: '2023-07-03',
  //     title: 'Sound of Freedom',
  //     video: false,
  //     vote_average: 8,
  //     vote_count: 442
  //   },
  //   {
  //     adult: false,
  //     backdrop_path: '/c6Splshb8lb2Q9OvUfhpqXl7uP0.jpg',
  //     genre_ids: [ 28, 53 ],
  //     id: 717930,
  //     original_language: 'en',
  //     original_title: 'Kandahar',
  //     overview: 'After his mission is exposed, an undercover CIA operative stuck deep in hostile territory in Afghanistan must fight his way out, alongside his Afghan translator, to an extraction point in Kandahar, all whilst avoiding elite enemy forces and foreign spies tasked with hunting them down.',
  //     popularity: 597.995,
  //     poster_path: '/lCanGgsqF4xD2WA5NF8PWeT3IXd.jpg',
  //     release_date: '2023-05-25',
  //     title: 'Kandahar',
  //     video: false,
  //     vote_average: 6.7,
  //     vote_count: 441
  //   },
  //   {
  //     adult: false,
  //     backdrop_path: '/8FhKnPpql374qyyHAkZDld93IUw.jpg',
  //     genre_ids: [ 9648, 53, 878 ],
  //     id: 536437,
  //     original_language: 'en',
  //     original_title: 'Hypnotic',
  //     overview: 'A detective becomes entangled in a mystery involving his missing daughter and a secret government program while investigating a string of reality-bending crimes.',
  //     popularity: 207.261,
  //     poster_path: '/mv362kHXz4Yr33wtQhqfcJWFM8G.jpg',
  //     release_date: '2023-05-11',
  //     title: 'Hypnotic',
  //     video: false,
  //     vote_average: 6.5,
  //     vote_count: 529
  //   },
  //   {
  //     adult: false,
  //     backdrop_path: '/9t0tJXcOdWwwxmGTk112HGDaT0Q.jpg',
  //     genre_ids: [ 27, 53 ],
  //     id: 890771,
  //     original_language: 'en',
  //     original_title: 'The Black Demon',
  //     overview: "Oilman Paul Sturges' idyllic family vacation turns into a nightmare when they encounter a ferocious megalodon shark that will stop at nothing to protect its territory. Stranded and under constant attack, Paul and his family must somehow find a way to get his family back to shore alive before it strikes again in this epic battle between humans and nature.",
  //     popularity: 141.932,
  //     poster_path: '/6ecSjKSjgIULyHfrfyyg9vgAI33.jpg',
  //     release_date: '2023-04-26',
  //     title: 'The Black Demon',
  //     video: false,
  //     vote_average: 6.3,
  //     vote_count: 490
  //   },
];
